# app/config/config.yml

liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        my_thumb:
            default_image: default.png
            quality: 100
            filters:
                thumbnail: 
                    size: [100, 100]
                    mode: outbound

        my_thumb_wine:
            default_image: default.png
            quality: 100
            filters:
                thumbnail: 
                    size: [115, 140]
                    mode: outbound

        my_thumb_wine_90:
            default_image: default.png
            quality: 100
            filters:
                rotate:
                    angle: 270
                thumbnail: 
                    size: [280, 230]
                    mode: outbound

        my_article_small:
            default_image: default.png
            quality: 100
            filters:
                thumbnail: 
                    size: [350, 350]
                    mode: outbound

        my_normal:
            default_image: default.png
            quality: 100
            filters:
                thumbnail: 
                    size: [470, 620]
                    mode: outbound

        my_large:
            default_image: default.png
            quality: 100
            filters:
                thumbnail: 
                    size: [1920, 1080]
                    mode: outbound