# app/config/config.yml

liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_thumb:
            quality: 100
            filters:

                rotate:
                    angle: 270

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: 
                    size: [124, 90]
                    mode: outbound

        my_normal:
            quality: 100
            filters:
                thumbnail: 
                    size: [470, 620]
                    mode: outbound

        my_large:
            quality: 100
            filters:
                thumbnail: 
                    size: [1920, 1080]
                    mode: outbound