doctrine:
    dbal:
        dbname:               dev
        host:                 localhost
        port:                 3306
        user:                 root
        password:             123
        driver:               pdo_mysql