home:
    path: /
    controller: App\Controller\DefaultController::index
wine:
    path: /wine
    controller: App\Controller\DefaultController::wineCatalogue
login:
    path: /login
    controller: App\Controller\SecurityController::login
    