home:
    path: /
    controller: App\Controller\DefaultController::index
wine:
    path: /wine
    controller: App\Controller\WineController::index
default:
    path: /index
    controller: App\Controller\DefaultController::index
